//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TimetableSys_T17
{
    public partial class Building
    {
        public Building()
        {
            this.Rooms = new HashSet<Room>();
            this.DeptInfoes = new HashSet<DeptInfo>();
        }
    
        public int buildingID { get; set; }
        public string buildingName { get; set; }
        public string buildingCode { get; set; }
        public Nullable<int> parkID { get; set; }
    
        public virtual Park Park { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<DeptInfo> DeptInfoes { get; set; }
    }
    
}
