//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TimetableSys_T17
{
    public partial class Module
    {
        public Module()
        {
            this.Requests = new HashSet<Request>();
            this.DegreeInfoes = new HashSet<DegreeInfo>();
            this.LecturerInfoes = new HashSet<LecturerInfo>();
        }
    
        public int moduleID { get; set; }
        public string modCode { get; set; }
        public string modTitle { get; set; }
        public Nullable<int> deptID { get; set; }
        public string part { get; set; }
        public Nullable<int> student { get; set; }
    
        public virtual DeptInfo DeptInfo { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<DegreeInfo> DegreeInfoes { get; set; }
        public virtual ICollection<LecturerInfo> LecturerInfoes { get; set; }
    }
    
}
