//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TimetableSys_T17
{
    public partial class Request
    {
        public Request()
        {
            this.Rooms = new HashSet<Room>();
            this.Facilities = new HashSet<Facility>();
            this.RoomRequests = new HashSet<RoomRequest>();
        }
    
        public int requestID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> moduleID { get; set; }
        public Nullable<int> sessionTypeID { get; set; }
        public Nullable<int> dayID { get; set; }
        public Nullable<int> periodID { get; set; }
        public Nullable<int> sessionLength { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> round { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> adhoc { get; set; }
        public string specialRequirement { get; set; }
        public Nullable<int> statusID { get; set; }
        public string week { get; set; }
    
        public virtual DayInfo DayInfo { get; set; }
        public virtual Module Module { get; set; }
        public virtual PeriodInfo PeriodInfo { get; set; }
        public virtual RoundInfo RoundInfo { get; set; }
        public virtual SessionTypeInfo SessionTypeInfo { get; set; }
        public virtual StatusInfo StatusInfo { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
        public virtual ICollection<RoomRequest> RoomRequests { get; set; }
    }
    
}
