//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TimetableSys_T17
{
    public partial class Room
    {
        public Room()
        {
            this.RoomRequests = new HashSet<RoomRequest>();
            this.Requests = new HashSet<Request>();
            this.Facilities = new HashSet<Facility>();
        }
    
        public int roomID { get; set; }
        public string roomCode { get; set; }
        public Nullable<int> buildingID { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> lab { get; set; }
        public Nullable<int> @private { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual ICollection<RoomRequest> RoomRequests { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
    }
    
}
