//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TimetableSys_T17
{
    public partial class RoundInfo
    {
        public RoundInfo()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int round { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
    
}
