//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace TimetableSys_T17
{
    public partial class TimetableDbEntities : DbContext
    {
        public TimetableDbEntities()
            : base("name=TimetableDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Building> Buildings { get; set; }
        public DbSet<DayInfo> DayInfoes { get; set; }
        public DbSet<DegreeInfo> DegreeInfoes { get; set; }
        public DbSet<DeptInfo> DeptInfoes { get; set; }
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<LecturerInfo> LecturerInfoes { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<Park> Parks { get; set; }
        public DbSet<PeriodInfo> PeriodInfoes { get; set; }
        public DbSet<Preference> Preferences { get; set; }
        public DbSet<Request> Requests { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<RoomRequest> RoomRequests { get; set; }
        public DbSet<RoundInfo> RoundInfoes { get; set; }
        public DbSet<SessionTypeInfo> SessionTypeInfoes { get; set; }
        public DbSet<StatusInfo> StatusInfoes { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
